using DeveloperStore.Application.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace DeveloperStore.Application.Services
{
    public class EmailService : IEmailService
    {
        public void Send(string toEmail, string subject, string body)
        {
            var fromAddress = new MailAddress("developer.store.rio2025@gmail.com", "Developer Store");
            var toAddress = new MailAddress(toEmail);
            string fromPassword = "hjey tmwa pgkf pvkt"; // app password generated by Google

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                Credentials = new NetworkCredential(fromAddress.Address, fromPassword)
            };

            using (var message = new MailMessage(fromAddress, toAddress)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
            {
                smtp.Send(message);
            }
        }
    }
}
